# Generated by Django 3.2.4 on 2021-06-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_auto_20210607_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='category',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ManyToManyField, to=settings.AUTH_USER_MODEL),
        ),
    ]
